apiVersion: skaffold/v4beta2
kind: Config
metadata: 
  name: local-dev
build:
  local:
    push: false
  tagPolicy:
    sha256: {}
  artifacts: 
    - image: ashura/django
      context: src/ashura
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
        - "**/*"
    - image: indra/nodejs
      context: src/indra
      docker:
        dockerfile: Dockerfile
      sync:
        infer:
        - "**/*"

deploy:
  kubectl: {}
manifests:
  kustomize:
    paths:
      - ./k8s/

  