apiVersion: batch/v1
kind: Job
metadata:
  name: ashura-db-migrate
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: db-migrate
        image: ashura/django:latest
        imagePullPolicy: Never
        command: ["python3",  "manage.py", "migrate"]
      restartPolicy: Never
