default_app_config = 'casho.casho.apps.MyAppConfiguration'

from .casho import  ErrorHandlingMiddleware,HealthCheckMiddleware,DatabaseConnectionError,IErrorStruct,CustomError,KafkaProducer,KafkaConsumer,serialize_message,deserialize_message