apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./manifests/ashura.postgres.yaml
  - ./manifests/indra.depl.yaml
  - ./manifests/ashura.depl.yaml
  - ./manifests/ingress.yaml
  - ./jobs/ashura-db.job.yaml
