apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaguya-app-deployment
  labels:
    app: kaguya
spec:
  replicas: 1 # number of replicas to run
  selector:
    matchLabels:
      app: kaguya
  template:
    metadata:
      labels:
        app: kaguya
    spec:
      initContainers:
        - name: kaguya-db-check
          image: mongo:5
          command: ['/bin/bash', '-c', 
            "until mongo 
              --host $MONGO_HOST 
              --port $MONGO_PORT 
              --eval 
              'quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)' --quiet; 
            do 
              echo 'Waiting for MongoDB'; 
              sleep 2; 
            done;
            echo 'MongoDB is ready!';"
          ]

          envFrom:
            - configMapRef:
                name: kaguya-config
      containers:
        - name: kaguya
          image: kaguya/nodejs
          args: ["start:inspect"]
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 3020 # port exposed by the container
          envFrom:
            - configMapRef:
                name: kaguya-config
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kaguya-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: kaguya-secret
                  key: JWT_KEY
          # livenessProbe:
          #   httpGet:
          #     path: /health/live/
          #     port: 3020
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 2
          #   periodSeconds: 5
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready/
          #     port: 3020
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 2
          #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kaguya-service
spec:
  selector:
    app: kaguya
  ports:
    - name: http
      protocol: TCP
      port: 3020 # port exposed by the service
      targetPort: 3020 # port exposed by the container
  type: ClusterIP # type of the service
