apiVersion: v1
kind: ConfigMap
metadata:
  name: kaguya-config
data:
  MONGO_INITDB_ROOT_USERNAME: "kaguya-user"
  MONGO_INITDB_DATABASE: "kaguya-db"
  MONGO_HOST: "kaguya-db-service"
  KAFKA_BROKER: "kafka-service:9092"
  MONGO_PORT: "27017"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
---
apiVersion: v1
kind: Secret
metadata:
  name: kaguya-secret
type: Opaque
data:
  # This should **not** be in version control
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
  JWT_KEY: ZGphbmdvLWluc2VjdXJlLStpNDBhXzJjaihwaGNlNGxzMmd6NWp1XnhxI2l2d3AmenBvNSp2Km5xK25vYyNjeDM2
