apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaguya-consumer-deployment
  labels:
    app: kaguya-consumer
spec:
  replicas: 1 # number of replicas to run
  selector:
    matchLabels:
      app: kaguya-consumer
  template:
    metadata:
      labels:
        app: kaguya-consumer
    spec:
      initContainers:
        - name: kaguya-db-check
          image: mongo:5
          command: ['/bin/bash', '-c', 
            "until mongo 
              --host $MONGO_HOST 
              --port $MONGO_PORT 
              --eval 
              'quit(db.runCommand({ ping: 1 }).ok ? 0 : 1)' --quiet; 
            do 
              echo 'Waiting for MongoDB'; 
              sleep 2; 
            done;
            echo 'MongoDB is ready!';"
          ]

          envFrom:
            - configMapRef:
                name: kaguya-config
      containers:
        - name: kaguya-consumer
          image: kaguya/nodejs
          args: ["consumer"]
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: kaguya-config
          env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kaguya-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          
