apiVersion: apps/v1
kind: Deployment
metadata:
  name: indra-app-deployment
  labels:
    app: indra
spec:
  replicas: 1 # number of replicas to run
  selector:
    matchLabels:
      app: indra
  template:
    metadata:
      labels:
        app: indra
    spec:
      containers:
        - name: indra
          image: indra/nodejs
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 3000 # port exposed by the container
          envFrom:
            - configMapRef:
                name: indra-config
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: indra-secret
                  key: JWT_KEY
          livenessProbe:
            httpGet:
              path: /health/live/
              port: 8000
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: indra-service
spec:
  selector:
    app: indra
  ports:
    - name: http
      protocol: TCP
      port: 3000 # port exposed by the service
      targetPort: 3000 # port exposed by the container
  type: ClusterIP # type of the service
