apiVersion: v1
kind: ConfigMap
metadata:
  name: ashura-postgres-config
data:
  POSTGRES_DB: "ashura-db"
  POSTGRES_USER: "ashura-user"
---
apiVersion: v1
kind: Secret
metadata:
  name: ashura-postgres-cred
type: Opaque
data:
  # This should **not** be in version control
  password: cGFzc3dvcmQ=
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ashura-postgres-statefulset
spec:
  serviceName: "ashura-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: ashura-postgres # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: ashura-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          envFrom:
            - configMapRef:
                name: ashura-postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ashura-postgres-cred
                  key: password
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
            initialDelaySeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
            initialDelaySeconds: 5
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: ashura-postgres-service
spec:
  selector:
    app: ashura-postgres
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP



