apiVersion: apps/v1
kind: Deployment
metadata:
  name: zetsu-deployment
  labels:
    app: zetsu
spec:
  replicas: 1 # number of replicas to run
  selector:
    matchLabels:
      app: zetsu
  template:
    metadata:
      labels:
        app: zetsu
    spec:
      containers:
        - name: zetsu
          image: zetsu/nodejs
          ports:
            - containerPort: 3010 # port exposed by the container
          envFrom:
            - configMapRef:
                name: zetsu-config
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zetsu-secret
                  key: MONGODB_PASSWORD            
---
apiVersion: v1
kind: Service
metadata:
  name: zetsu-service
spec:
  selector:
    app: zetsu
  ports:
    - name: http
      protocol: TCP
      port: 3010 # port exposed by the service
      targetPort: 3010 # port exposed by the container
  type: ClusterIP # type of the service
