apiVersion: v1
kind: ConfigMap
metadata:
  name: zetsu-config
data:
  MONGO_INITDB_ROOT_USERNAME: "zetsu-user"
  MONGO_INITDB_DATABASE: "zetsu-db"
  MONGO_HOST: "zetsu-db-service"
  KAFKA_BROKER: "kafka-service:9092"
  MONGO_PORT: "27017"
---
apiVersion: v1
kind: Secret
metadata:
  name: zetsu-secret
type: Opaque
data:
  # This should **not** be in version control
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
  JWT_KEY: "django-insecure-+i40a_2cj(phce4ls2gz5ju^xq#ivwp&zpo5*v*nq+noc#cx36"
